# Generated by Django 5.2.2 on 2025-06-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
