# Generated by Django 5.2.2 on 2025-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_registrojammer'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
