# Generated by Django 5.2.2 on 2025-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('numero_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], max_length=10)),
                ('codigo', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
